mysite/invoice/urls.py
from django.urls import path
from .views import *

app_name = "invoice"
urlpatterns = [
    path('', InvoiceList.as_view(), name='list'),
    path('detail/<int:pk>', InvoiceDetail.as_view(), name='detail'),
    path('edit/<int:pk>', InvoiceUpdate.as_view(), name='edit'),
    path('submit/<int:pk>', InvoiceUpdate.as_view(), {'process': 'submit'}, name='submit'),
    path('cancel/<int:pk>', InvoiceUpdate.as_view(), {'process': 'cancel'}, name='cancel'),
    path('create/', InvoiceCreate.as_view(), name='create'),

    path('add_line/', InvoiceLineCreate.as_view(), name='add_line'),
    path('delete_line/<int:pk>', InvoiceLineDelete.as_view(), name='delete_line'),
    path('edit_line/<int:pk>', InvoiceLineEdit.as_view(), name='edit_line'),

    path('create_stockentry/<int:invo_id>', CreateStockEntry.as_view(), name='create_stockentry'),
    path('list_stockentry/<int:invo_id>', ListStockEntry.as_view(), name='create_sotckentry'),
]

mysite/main/urls.py
from django.urls import path, include
from .views import MainView, MainLoginView
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('login/', MainLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='main_url'), name='logout'),
    path('', MainView.as_view(), name='main_url'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('invoice/', include('invoice.urls')),
    path('payment/', include('payment.urls')),
    path('partner/', include('partner.urls')),
    path('stock/', include('stock.urls')),
    path('', include('main.urls')),
]

mysite/invoice/models.py
from django.db import models
from django.urls import reverse
from product.models import Product
from partner.models import Partner
# import stock # to avoid circular import
from django.dispatch import receiver
from django.db.models.signals import post_save, post_delete
from main.models import NamingSeries as NS

INVO_TYPE = [
    ('sell', 'Sell'),
    ('purchase', 'Purchase'),
]
INVO_STATUS = [
    ('draft', 'Draft'),
    ('submitted', 'Submitted'),
    ('cancelled', 'Cancelled'),
]
STOCK_STATUS = [
    ('pending', 'Pending'),
    ('partial', 'Partial'),
    ('complete', 'Complete'),
]
PAY_STATUS = [
    ('pending', 'Pending'),
    ('partial', 'Partial'),
    ('complete', 'Complete'),
    ('overdue', 'Overdue'),
]

class Invoice(models.Model):
    code = models.CharField(max_length=12, null=True)
    date = models.DateField(null=True)
    partner = models.ForeignKey(Partner, related_name='invoice_partner', on_delete=models.SET_NULL, null=True)
    type = models.CharField(choices=INVO_TYPE, default='', null=True, max_length=10)
    status = models.CharField(choices=INVO_STATUS, default='draft', null=True, max_length=10)
    total = models.DecimalField(default=0.0, decimal_places=2, max_digits=12)
    qty_status = models.CharField(choices=STOCK_STATUS, default='pending', null=True, max_length=10)
    pay_status = models.CharField(choices=PAY_STATUS, default='pending', null=True, max_length=10)
    outstanding = models.DecimalField(default=0.0, decimal_places=2, max_digits=12)
    payments = models.DecimalField(default=0.0, decimal_places=2, max_digits=12)

    class Meta:
        ordering = ['code']

    def __str__(self):
        return self.code

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.id:
            if self.type == 'purchase':
                self.code = NS.get_series(serie='PINV')
            if self.type == 'sell':
                self.code = NS.get_series(serie='SINV')
        return super().save(force_insert, force_update, using, update_fields)

    def get_absolute_url(self):
        return reverse('invoice:detail', args=[self.id])

    @classmethod
    def submit_invoice(cls, id=None):
        if id:
            invo = cls.objects.get(pk=id)
            if InvoiceLine.submit_invoice_lines(invo):
                invo.status = 'submitted'
                invo.outstanding = invo.total
                invo.save()

    @classmethod
    def cancel_invoice(cls, id=None):
        if id:
            invo = cls.objects.get(pk=id)
            if InvoiceLine.cancel_invoice_lines(invo):
                invo.status = 'cancelled'
                invo.save()

    @classmethod
    def calculate_total(cls, id=None):
        total = 0
        if id:
            invo = cls.objects.get(pk=id)
            lines = InvoiceLine.objects.all().filter(parent=invo.id)
            for line in lines:
                total += line.total

            invo.total = total
            invo.outstanding = total - invo.payments
            invo.save()
            
    def get_ste_count(self):
        from stock.models import StockEntry
        ste = StockEntry.objects.filter(parent=self.id).count()
        return ste

    def get_pay_count(self):
        from paymententry.models import PaymentEntry
        ste = PaymentEntry.objects.filter(parent=self.id).count()
        return ste


class InvoiceLine(models.Model):
    item = models.ForeignKey(Product, related_name='invoice_line_item', on_delete=models.SET_NULL, null=True)
    parent = models.ForeignKey(Invoice, related_name='invoice_line_parent', on_delete=models.SET_NULL, null=True)
    qty = models.DecimalField(default=0.0, decimal_places=2, max_digits=12)
    price = models.DecimalField(default=0.0, decimal_places=2, max_digits=12)
    type = models.CharField(choices=INVO_TYPE, default='', null=True, max_length=10)
    status = models.CharField(choices=INVO_STATUS, default='draft', null=True, max_length=10)
    qty_status = models.CharField(choices=STOCK_STATUS, default='pending', null=True, max_length=10)
    qty_stock = models.DecimalField(default=0.0, decimal_places=2, max_digits=12)
    total = models.DecimalField(default=0.0, decimal_places=2, max_digits=12)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.total = self.qty * self.price
        return super().save(force_insert, force_update, using, update_fields)

    @classmethod
    def submit_invoice_lines(cls, parent=None):
        lines = cls.objects.all().filter(parent=parent.id)
        if lines:
            for line in lines:
                line.status = 'submitted'
                line.qty_stock = line.qty
                line.save()
            return True
        else:
            return False

    @classmethod
    def cancel_invoice_lines(cls, parent=None):
        lines = cls.objects.all().filter(parent=parent.id)
        if lines:
            for line in lines:
                line.status = 'cancelled'
                line.save()
            return True
        else:
            return False

    def update_qty_status(self, invo_line=None):
        invl = invo_line

        if invl.qty_stock <= 0:
            invl.qty_status = 'complete'
            invl.parent.qty_status = 'complete'

        if invl.qty_stock > 0 and invl.qty_stock < invl.qty:
            invl.qty_status = 'partial'
            # if any line is partial invoice will also turn partial
            invl.parent.qty_status = 'partial'

        invl.save()
        invl.parent.save()
        

@receiver(post_save, sender=InvoiceLine)
def save_calculate_inv_lines(sender, instance, **kwargs):
    instance.parent.calculate_total(instance.parent.id)

@receiver(post_delete, sender=InvoiceLine)
def delete_calculate_inv_lines(sender, instance, **kwargs):
    instance.parent.calculate_total(instance.parent.id)

mysite/invoice/forms.py
from django import forms
from django.forms import inlineformset_factory
from .models import Invoice, InvoiceLine


class InvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = [
                'date',
                'partner',
                'type',
                ]
        widgets = {
                'date': forms.DateInput(attrs={'class': 'form-control container col', 'type': 'date'}),
                'partner': forms.Select(attrs={'class': 'form-control'}),
                'type': forms.Select(attrs={'class': 'form-control'}),
                }


class InvoiceLineForm(forms.ModelForm):
    class Meta:
        model = InvoiceLine
        fields = [
            'parent',
            'item',
            'qty',
            'price'
        ]
        widgets = {
            'parent': forms.HiddenInput(),
        }


InvoiceLineIF = inlineformset_factory(
    Invoice,
    InvoiceLine,
    fields= "__all__",
    form=InvoiceLineForm,
    extra= 1,
)

mysite/invoice/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect
from django.http import JsonResponse 
from .models import Invoice, InvoiceLine
from .forms import InvoiceForm, InvoiceLineIF, InvoiceLineForm
from stock.models import StockEntry, StockEntryLine
from stock.forms import StockEntryForm, StockEntryLineForm, StockEntryLineIF
from main.views import BaseView


class InvoiceList(BaseView, ListView):
    model = Invoice
    template_name = 'invoice/list.html'
    paginate_by = 8
    permission_required = 'invoice.view_invoice'

    def is_ajax(self, request):
        return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

    def get(self, *args, **kwargs):
        if self.is_ajax(request=self.request):
            ajax_val = self.request.GET['term']
            invo_obj = Invoice.objects.all().filter(code__icontains=ajax_val)
            invoices = list(invo_obj.values())
            return JsonResponse(invoices, safe=False)

        return super(InvoiceList, self).get(*args, **kwargs)


class InvoiceDetail(BaseView, DetailView):
    model = Invoice
    form_class = InvoiceForm
    template_name = 'invoice/detail.html'
    fields = "__all__"
    pk_url_kwarg = 'pk'
    permission_required = 'invoice.view_invoice'

    def is_ajax(self, request):
        return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

    def get(self, *args, **kwargs):
        if self.is_ajax(request=self.request):
            inv_data = Invoice.objects.filter(id=kwargs.get('pk')).values()[0]
            return JsonResponse(inv_data, safe=False)

        return super(InvoiceDetail, self).get(*args,**kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lines = InvoiceLine.objects.all().filter(parent=self.kwargs['pk'])
        new_line = InvoiceLineForm(initial={'parent':self.object})
        context['new_line'] = new_line
        context['lines'] = lines
        return context
        

class InvoiceCreate(BaseView, CreateView):
    model = Invoice
    form_class = InvoiceForm
    template_name = 'invoice/create.html'
    success_url = reverse_lazy('invoice:list')
    permission_required = 'invoice.add_invoice'

    def get_success_url(self):
        return reverse('invoice:detail', kwargs={'pk':self.object.id})


class InvoiceUpdate(BaseView, UpdateView):
    model = Invoice
    form_class = InvoiceForm
    template_name = 'invoice/detail.html'
    fields = "__all__"
    pk_url_kwarg = 'pk'
    permission_required = 'invoice.change_invoice'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lines = InvoiceLine.objects.all().filter(parent=self.kwargs['pk'])
        new_line = InvoiceLineForm(initial={'parent':self.object})
        context['new_line'] = new_line
        context['lines'] = lines
        return context

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        if kwargs.get('process') == 'submit':
            obj.submit_invoice(obj.id)
        
        if kwargs.get('process') == 'cancel':
            obj.cancel_invoice(obj.id)

        return redirect('invoice:detail', pk=obj.id)


class InvoiceLineCreate(BaseView, CreateView):
    model = InvoiceLine
    form_class = InvoiceLineForm
    template_name = 'invoice/add_line.html'
    pk_url_kwarg = 'pk'
    permission_required = 'invoiceline.add_invoiceline'

    def post(self, request, *args, **kwargs):
        return super(InvoiceLineCreate, self).post(request, *args, **kwargs)

    def get_success_url(self):
        pk = self.request.POST['parent']
        return reverse('invoice:detail', kwargs={'pk':pk})


class InvoiceLineEdit(BaseView, UpdateView):
    model = InvoiceLine
    form_class = InvoiceLineForm
    template_name = 'invoice/edit_line.html'
    pk_url_kwarg = 'pk'
    permission_required = 'invoiceline.change_invoiceline'

    def get_success_url(self):
        line = InvoiceLine.objects.get(pk=self.kwargs['pk'])
        return reverse('invoice:detail', kwargs={'pk':line.parent.id})


class InvoiceLineDelete(BaseView, DeleteView):
    model = InvoiceLine
    template_name = 'invoice/delete_line.html'
    pk_url_kwarg = 'pk'
    permission_required = 'invoiceline.delete_invoiceline'

    def get_success_url(self):
        return reverse('invoice:detail', kwargs={'pk':self.object.parent.id})


class CreateStockEntry(BaseView, CreateView):
    model = StockEntry
    form_class = StockEntryForm
    template_name = 'invoice/create_ste.html'
    pk_url_kwarg = 'pk'
    permission_required = 'stockentry.add_stockentry'

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        # add val for template 
        context = super(CreateStockEntry, self).get_context_data(**kwargs)
        invo_obj = Invoice.objects.get(pk=self.kwargs['invo_id'])
        context['invo_obj'] = invo_obj

        context['form'] = StockEntryForm({
            'type': 'delivery' if invo_obj.type == 'sell' else 'receipt',
            'date': invo_obj.date
        })
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        self.object = form.save()
        self.object.parent = context['invo_obj']
        invoice_lines = InvoiceLine.objects.all().filter(parent=context['invo_obj'].id)
        for il in invoice_lines:
            if il.qty_stock > 0:
                line = StockEntryLineForm({
                    'invo_line': il,
                    'parent': self.object,
                    'item': il.item,
                    'qty': il.qty_stock,
                    'price': il.price,
                    })
                if line.is_valid():
                    line.save()

        return super(CreateStockEntry, self).form_valid(form)

    def get_success_url(self):
        return reverse('stock:detail', kwargs={'pk':self.object.id})


class ListStockEntry(BaseView, ListView):
    model = StockEntry
    template_name = 'invoice/list_ste.html'
    paginate_by = 5
    permission_required = 'stockentry.view_stockentry'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        invo_obj = Invoice.objects.get(pk=self.kwargs['invo_id'])
        ste_objs = StockEntry.objects.filter(parent=invo_obj.id)
        context['invoice'] = invo_obj
        context['object_list'] = ste_objs
        context['ste_count'] = ste_objs.count()
        return context

mysite/invoice/templates/invoice/add_line.html
{% load static %}
{% block add_line %}
<script src="{% static 'js/invoice.js' %}" type="text/javascript"></script>
<link href="{% static 'css/invoice.css' %}" rel="stylesheet" />
<form action="{% url 'invoice:add_line' %}" method='POST'>
  <div class="modal-header">
    <h5 class="modal-title">Add Item</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    {% csrf_token %}
    {{form.as_table}}
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Add</button>
  </div>
</form>
{% endblock add_line %}

mysite/invoice/templates/invoice/create_ste.html
{% load static %}
{% block content %}
<script src="{% static 'js/stock.js' %}" type="text/javascript"></script>
<link href="{% static 'css/stock.css' %}" rel="stylesheet" />
<form action="{% url 'invoice:create_stockentry' invo_id=invo_obj.id%}" method="POST">
  <div class="modal-header">
    <h5 class="modal-title">Select date for delivery</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    {% csrf_token %}
    {{form.as_table}}
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary ">Save</button>
  </div>
</form>
{% endblock content %}

mysite/invoice/templates/invoice/detail.html
{% extends 'main/main.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/invoice.js' %}" type="text/javascript"></script>
<link href="{% static 'css/invoice.css' %}" rel="stylesheet"/>
<div class="container-fluid rounded border border-dark mt-2 p-2">
  <div class="row p-1">
    <div class="col-8">
      <div class="row">
        <h3>Invoice {{ object.code }}</h3>
      </div>
      <div class="row">
        <div class="col-4">
          {{ object.date.label }}
          {{ object.date }}
        </div>
        <div class="col-4">
          {{ object.status.label }}
          {{ object.get_status_display }}
        </div>
      </div>
      <div class="row">
        <div class="col-4">
          {{ object.partner.label }}
          {{ object.partner }}
        </div>
        <div class="col-4">
          {{ object.type.label }}
          {{ object.get_type_display }}
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="row p-1">
        <div class="col-8">
        </div>
        {% if object.status == 'draft' %}
          <div class="col-4 container rounded border text-center bg-secondary">
        {% elif object.status == 'submitted' %}
          <div class="col-4 container rounded border text-center bg-primary">
        {% elif object.status == 'cancelled' %}
          <div class="col-4 container rounded border text-center bg-danger">
        {% endif %}
          <b>{{ object.get_status_display }}</b>
        </div>
      </div>
      {% if object.status == 'submitted' %}
        <div class="row p-1">
          <div class="col-8">
          </div>
          {% if object.qty_status == 'pending' %}
          <div onclick="list_ste({{object.id}})" class="col-4 container rounded border border-dark text-center bg-secondary">
          {% elif object.qty_status == 'partial' %}
          <div onclick="list_ste({{object.id}})" class="col-4 container rounded border border-dark text-center bg-warning">
          {% elif object.qty_status == 'complete' %}
          <div onclick="list_ste({{object.id}})" class="col-4 container rounded border border-dark text-center bg-success">
          {% endif %}
            <b class="fs-5">
                <span class="material-icons align-middle">
                local_shipping more_vert
              </span> 
              {{ object.get_ste_count}}

            </b>
          </div>
        </div>
        <div class="row p-1">
          <div class="col-8">
          </div>
          <div class="col-4 container rounded border border-dark text-center">
            <b class="fs-5">
              <span class="material-icons align-middle">
                payments more_vert
              </span>
              0
            </b>
          </div>
        </div>
      {% endif %}
    </div>
  </div>
  <!-- <div class="container rounded border p-1"> -->
  <div class="row p-2">
    <div class="col-12 container-fluid rounded border border-dark">
      <table class="table table-hover border-dark mb-0">
        <thead>
          {% if object.status == 'draft' %}
            <th style="width:50%">Code</th>
            <th class="text-end" style="width:15%">QTY</th>
            <th class="text-end" style="width:15%">Price</th>
            <th class="text-end" style="width:15%">Total</th>
            <th class="text-end" style="width:5%"></th>
          {% else %}
            <th style="width:55%">Code</th>
            <th class="text-end" style="width:15%">QTY</th>
            <th class="text-end" style="width:15%">Price</th>
            <th class="text-end" style="width:15%">Total</th>
          {% endif %}
        </thead>
        <tbody>
          {% for line in lines %}
            {% if object.status == 'draft' %}
              <tr onclick="edit_line({{line.id}})">
            {% else %}
              <tr>
            {% endif %}
            {% if object.status == 'draft' %}
              <td class="hidden">{{ line.id }}</td>
              <td style="width:50%">{{ line.item }}</td>
              <td class="text-end" style="width:15%">{{ line.qty }}</td>
              <td class="text-end" style="width:15%">{{ line.price }}</td>
              <td class="text-end" style="width:15%">{{ line.total }}</td>
              <td class="text-end" style="width:5%">
                <div>
                  <span onclick="delete_line({{line.id}})" type="button" class="material-icons">
                    delete
                  </span>
              </td>
            {% else %}
              <td class="hidden">{{ line.id }}</td>
              <td style="width:55%">{{ line.item }}</td>
              <td class="text-end" style="width:15%">{{ line.qty }}</td>
              <td class="text-end" style="width:15%">{{ line.price }}</td>
              <td class="text-end" style="width:15%">{{ line.total }}</td>
            {% endif %}
            </tr>
          {% endfor %}
          <tr class="text-end">
            <td></td>
            <td></td>
            <td>Total:</td>
            <td>{{ object.total }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row p-2">
      <div class=" col-8">
      </div>
      <div class="col-4 container rounded border border-dark">
        <table class="table mb-0 border-dark">
          <tr>
            <td>Total:</td>
            <td>{{ object.total }}</td>
          </tr>
          <tr>
            <td>Payments:</td>
            <td>{{ object.payments }}</td>
          </tr>
          <tr>
            <td>Outstanding:</td>
            <td>{{ object.outstanding }}</td>
          </tr>
        </table>
      </div>
  </div>

  <div class="row p-0 mb-1">
    {% if object.status == 'draft' %}
    <div class="col-6">
      <button onclick="add_line({{object.id}})" id="add-item-btn" type="button" class="btn btn-primary">
        Add Item
      </button>
    </div>
    <div class="col-6">
        <button id="submit-modal-btn" type="button" class="btn btn-success pull-right" data-bs-toggle="modal"
          data-bs-target="#submitInvoiceModal">
          Submit
        </button>
    </div>
    {% endif %}
    {% if object.status == 'submitted' %}
    <div class="col-12">
        <button id="cancel-modal-btn" type="button" class="btn btn-danger pull-right" data-bs-toggle="modal"
          data-bs-target="#cancelInvoiceModal">
          Cancel
        </button>
    </div>
    {% endif %}
  <div>

  <!-- Item Modal -->
  <div class="modal fade" id="itemModal" data-backdrop="true" tabindex="-1" aria-labelledby="itemModal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content" id="item-modal-content">
        <!-- ITEM -->
      </div>
    </div>
  </div>

  <!-- Submit Modal -->
  <div class="modal fade" id="submitInvoiceModal" tabindex="-1" aria-labelledby="submitInvoiceModal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Submit ?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="{% url 'invoice:submit' pk=object.id%}" method='POST'>
            {% csrf_token %}
            <div class="row">
              <div class="col-6">
                <h5> {{ object.code }} </h5>
              </div>
              <div class="col-6">
                <div class="pull-right">
                  <button type="submit" class="btn btn-primary">Yes</button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <!-- Cancel Modal -->
  <div class="modal fade" id="cancelInvoiceModal" tabindex="-1" aria-labelledby="cancelSteModal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Cancel ?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="{% url 'invoice:cancel' pk=object.id%}" method='POST'>
            {% csrf_token %}
            <div class="row">
              <div class="col-6">
                <h5> {{ object.code }} </h5>
              </div>
              <div class="col-6">
                <div class="pull-right">
                  <button type="submit" class="btn btn-primary">Yes</button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

</div>
{% endblock content %}

mysite/invoice/templates/invoice/list.html
{% extends 'main/main.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/invoice.js' %}" type="text/javascript"></script>
<link href="{% static 'css/invoice.css' %}" rel="stylesheet"/>
<div class="container rounded border border-dark mt-2">
  <table class="table table-hover mb-0">
    <thead>
      <th style="width:15%">Code</th>
      <th style="width:15%">Date</th>
      <th style="width:30%">Partner</th>
      <th style="width:10%" class="text-center">Type</th>
      <th style="width:10%" class="text-center">Status</th>
      <th style="width:10%">Total</th>
    </thead>
    <tbody>
      {% for invoice in object_list %}
      <tr onclick="window.location='detail/{{invoice.id}}'">
        <td style="width:15%">{{ invoice.code }}</td>
        <td style="width:15%">{{ invoice.date }}</td>
        <td style="width:30%">{{ invoice.partner }}</td>
        <td style="width:10%" class="text-center">{{ invoice.get_type_display }}</td>
        <td style="width:10%">
          {% if invoice.status == 'draft' %}
            <div class="bg-secondary text-white text-center border border-dark rounded">
          {% elif invoice.status == 'submitted' %}
            <div class="bg-primary text-white text-center border border-dark rounded">
          {% elif invoice.status == 'cancelled' %}
            <div class="bg-danger text-white text-center border border-dark rounded">
          {% endif %}
            {{ invoice.get_status_display }}
          </div>
        </td>
        <td style="width:10%">{{ invoice.total }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% include 'main/footer.html' %}
</div>
{% endblock content %}

mysite/invoice/templates/invoice/list_ste.html
{% load static %}
{% block list_ste %}
<script src="{% static 'js/stock.js' %}" type="text/javascript"></script>
<link href="{% static 'css/stock.css' %}" rel="stylesheet" />
<div class="modal-header">
  <h5 class="modal-title">Invoice ({{invoice}}) Stock Entry List ({{ste_count}})</h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
  <table class="table table-hover mb-0">
    <thead>
      <th style="width:30%">Code</th>
      <th style="width:20%">Date</th>
      <th style="width:20%">Parent</th>
      <th class="text-center" style="width:10%">Type</th>
      <th class="text-center" style="width:10%">Status</th>
    </thead>
    <tbody>
      {% for stock in object_list %}
      <tr onclick="window.location='/stock/detail/{{stock.id}}'" )>
        <td style="width:20%">{{ stock.code }}</td>
        <td style="width:20%">{{ stock.date }}</td>
        <td style="width:20%">{{ stock.parent }}</td>
        <td class="text-center" style="width:10%">{{ stock.get_type_display }}</td>
          <td class="text-center" style="width:10%">
          {% if stock.status == 'draft' %}
            <div class="bg-secondary text-white text-center border border-dark rounded">
          {% elif stock.status == 'submitted' %}
            <div class="bg-primary text-white text-center border border-dark rounded">
          {% elif stock.status == 'cancelled' %}
            <div class="bg-danger text-white text-center border border-dark rounded">
          {% endif %}
          {{ stock.get_status_display }}
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<div class="modal-footer">
  <button class="btn btn-primary">List All</button>
  <div onclick="create_ste({{invoice.id}})" class="btn btn-success">
    Create
  </div>

</div>
{% endblock list_ste %}