mysite/invoice/urls.py
from django.urls import path
from .views import *

app_name = "invoice"
urlpatterns = [
    path('', InvoiceList.as_view(), name='list'),
    path('detail/<int:pk>', InvoiceDetail.as_view(), name='detail'),
    path('edit/<int:pk>', InvoiceUpdate.as_view(), name='edit'),
    path('submit/<int:pk>', InvoiceUpdate.as_view(), {'process': 'submit'}, name='submit'),
    path('cancel/<int:pk>', InvoiceUpdate.as_view(), {'process': 'cancel'}, name='cancel'),
    path('create/', InvoiceCreate.as_view(), name='create'),

    path('add_line/', InvoiceLineCreate.as_view(), name='add_line'),
    path('delete_line/<int:pk>', InvoiceLineDelete.as_view(), name='delete_line'),
    path('edit_line/<int:pk>', InvoiceLineEdit.as_view(), name='edit_line'),

    path('create_stockentry/<int:invo_id>', CreateStockEntry.as_view(), name='create_stockentry'),
    path('list_stockentry/<int:invo_id>', ListStockEntry.as_view(), name='create_sotckentry'),
]

mysite/main/urls.py
from django.urls import path, include
from .views import MainView, MainLoginView
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('login/', MainLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='main_url'), name='logout'),
    path('', MainView.as_view(), name='main_url'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('invoice/', include('invoice.urls')),
    path('payment/', include('payment.urls')),
    path('partner/', include('partner.urls')),
    path('stock/', include('stock.urls')),
    path('', include('main.urls')),
]

mysite/stock/urls.py
from django.urls import path
from .views import *

app_name = "stock"
urlpatterns = [
    path('', StockEntryList.as_view(), name='list'),
    path('detail/<int:pk>', StockEntryDetail.as_view(), name='detail'),
    # path('edit/<int:pk>', StockEntryUpdate.as_view(), name='edit'),
    path('submit/<int:pk>', StockEntryUpdate.as_view(), {'process': 'submit'}, name='submit'),
    path('cancel/<int:pk>', StockEntryUpdate.as_view(), {'process': 'cancel'}, name='cancel'),
    path('create/', StockEntryCreate.as_view(), name='create'),

    path('add_line/', StockEntryLineCreate.as_view(), name='add_line'),
    path('edit_line/<int:pk>', StockEntryLineEdit.as_view(), name='edit_line'),
    path('delete_line/<int:pk>', StockEntryLineDelete.as_view(), name='delete_line'),
]

mysite/stock/models.py
from django.urls import reverse
from django.db import models
from product.models import Product
from invoice.models import Invoice, InvoiceLine
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from main.models import NamingSeries as NS

ENTRY_STATUS = [
    ('draft', 'Draft'),
    ('submitted', 'Submitted'),
    ('cancelled', 'Cancelled'),
]
ENTRY_TYPE = [
    ('transfer', 'Transfer'),
    ('issue', 'Issue'),
    ('delivery', 'Delivery'),
    ('receipt', 'Receipt'),
]

class StockEntry(models.Model):
    code = models.CharField(max_length=10, null=True)
    date = models.DateField(null=True)
    type = models.CharField(choices=ENTRY_TYPE, default='', null=True, max_length=10)
    status = models.CharField(choices=ENTRY_STATUS, default='draft', null=True, max_length=10)
    total = models.DecimalField(default=0.0, decimal_places=2, max_digits=12)
    parent = models.ForeignKey(Invoice, related_name='ste_parent', on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ['-code']

    def __str__(self):
        return self.code

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.id:
            if self.type == 'transfer':
                self.code = NS.get_series(serie='TSTE')
            if self.type == 'issue':
                self.code = NS.get_series(serie='ISTE')
            if self.type == 'delivery':
                self.code = NS.get_series(serie='DSTE')
            if self.type == 'receipt':
                self.code = NS.get_series(serie='RSTE')
        
        # FIXME dont calculate total fom post_save
        # when ste create from invoice only from save method

        else:
            total = 0
            lines = StockEntryLine.objects.filter(parent=self.id)
            for line in lines:
                total += line.total
            self.total = total
        return super().save(force_insert, force_update, using, update_fields)

    @classmethod
    def submit_stock_entry(cls, id=None):
        if id:
            ste = cls.objects.get(pk=id)
            if StockEntryLine.submit_stock_lines(ste):
                ste.status = 'submitted'
                ste.save()

    @classmethod
    def cancel_stock_entry(cls, id=None):
        if id:
            ste = cls.objects.get(pk=id)
            ste.status = 'cancelled'
            ste.save()

    @classmethod
    def calculate_total(cls, id=None):
        if id:
            total = 0
            lines = StockEntryLine.objects.filter(parent=id)
            for line in lines:
                total += line.total
            ste = cls.objects.get(pk=id)
            ste.total = total
            ste.save()
            

class StockEntryLine(models.Model):
    item = models.ForeignKey(Product, related_name='str_line_item', on_delete=models.SET_NULL, null=True)
    parent = models.ForeignKey(StockEntry, related_name='ste_line_parent', on_delete=models.SET_NULL, null=True)
    qty = models.DecimalField(default=0.0, decimal_places=2, max_digits=10)
    price = models.DecimalField(default=0.0, decimal_places=2, max_digits=10)
    status = models.CharField(choices=ENTRY_STATUS, default='draft', null=True, max_length=10)
    total = models.DecimalField(default=0.0, decimal_places=2, max_digits=10)
    invo_line = models.ForeignKey(InvoiceLine, related_name='invo_line_parent', on_delete=models.SET_NULL, null=True, blank=True)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.total = self.qty * self.price
        return super().save(force_insert, force_update, using, update_fields)

    @classmethod
    def submit_stock_lines(cls, parent=None):
        lines = cls.objects.all().filter(parent=parent.id)
        if lines: 
            for line in lines:
                if line.item.type == 'stockable':
                    if line.invo_line:
                        line.invo_line.qty_stock = line.invo_line.qty_stock - line.qty
                        line.invo_line.save()
                        line.invo_line.update_qty_status(line.invo_line)
                    if parent.type == 'receipt':
                        if line.item.update_product_stock(line, type='in'):
                            line.status = 'submitted'
                            line.save()
                    if parent.type == 'delivery':
                        if line.item.update_product_stock(line, type='out'):
                            line.status = 'submitted'
                            line.save()
            return True
        else:
            return False


    @classmethod
    def cancel_stock_lines(cls, parent=None):
        lines = cls.objects.all().filter(parent=parent)
        if lines:
            for line in lines:
                line.status = 'cancelled'
                line.save()
            return True
        else:
            return False

@receiver(post_save, sender=StockEntryLine)
def save_calculate_ste_lines(sender, instance, **kwargs):
    # FIXME dont calculate when create from invoice
    instance.parent.calculate_total(instance.parent.id)

@receiver(post_delete, sender=StockEntryLine)
def delete_calculate_ste_lines(sender, instance, **kwargs):
    instance.parent.calculate_total(instance.parent.id)

mysite/stock/forms.py
from django import forms
from django.forms import inlineformset_factory
from .models import StockEntry, StockEntryLine


class StockEntryForm(forms.ModelForm):
    class Meta:
        model = StockEntry
        fields = [
            'date',
            'type',
        ]
        widgets = {
            'date': forms.DateInput(attrs={'class': 'form-control container col', 'type': 'date'}),
            'type': forms.Select(attrs={'class': 'form-control'}),
        }


class StockEntryLineForm(forms.ModelForm):
    class Meta:
        model = StockEntryLine
        fields = [
            'parent',
            'item',
            'qty',
            'price',
            'invo_line',
        ]
        widgets = {
            'parent': forms.HiddenInput(),
            'invo_line': forms.HiddenInput(),
        }

StockEntryLineIF= inlineformset_factory(
    StockEntry,
    StockEntryLine,
    fields= "__all__",
    form=StockEntryLineForm,
    extra= 0,
)

mysite/stock/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect
from .models import StockEntry, StockEntryLine
from .forms import StockEntryForm, StockEntryLineForm, StockEntryLineIF
from main.views import BaseView


class StockEntryList(BaseView, ListView):
    model = StockEntry
    template_name = 'stock/list.html'
    paginate_by = 8
    permission_required = 'stockentry.view_stockentry'


class StockEntryDetail(BaseView, DetailView):
    model = StockEntry
    form_class = StockEntryForm
    template_name = 'stock/detail.html'
    fields = "__all__"
    pk_url_kwarg = 'pk'
    permission_required = 'stockentry.view_stockentry'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lines = StockEntryLine.objects.all().filter(parent=self.kwargs['pk'])
        new_line = StockEntryLineForm(initial={'parent':self.object})
        context['new_line'] = new_line
        context['lines'] = lines
        return context
        

class StockEntryCreate(BaseView, CreateView):
    model = StockEntry
    form_class = StockEntryForm
    template_name = 'stock/create.html'
    permission_required = 'stockentry.add_stockentry'

    def get_success_url(self):
        return reverse('stock:detail', kwargs={'pk':self.object.id})


class StockEntryUpdate(BaseView, UpdateView):
    model = StockEntry
    form_class = StockEntryForm
    formset_class = StockEntryLineIF
    template_name = 'stock/detail.html'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('stock:detail')
    permission_required = 'stockentry.change_stockentry'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     lines = StockEntryLine.objects.all().filter(parent=self.kwargs['pk'])
    #     new_line = StockEntryLineForm(initial={'parent':self.object})
    #     context['new_line'] = new_line
    #     context['lines'] = lines
    #     return context

    # def get_success_url(self):
    #     pk = self.kwargs['pk']
    #     return reverse('stock:detail', kwargs={'pk':pk})

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        if kwargs.get('process') == 'submit':
            obj.submit_stock_entry(obj.id)
        
        if kwargs.get('process') == 'cancel':
            obj.cancel_stock_entry(obj.id)

        return redirect('stock:detail', pk=obj.id)

class StockEntryLineCreate(BaseView, CreateView):
    model = StockEntryLine
    form_class = StockEntryLineForm
    template_name = 'stock/add_line.html'
    pk_url_kwarg = 'pk'
    permission_required = 'stockentryline.add_stockentryline'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['parent'] = self.kwargs['pk']
    #     return context

    def get_success_url(self):
        # pk = self.kwargs['pk']
        # parent = StockEntry.objects.get(pk=self.kwargs['pk'])
        parent_id = self.request.POST['parent']
        return reverse('stock:detail', kwargs={'pk':parent_id})


class StockEntryLineEdit(BaseView, UpdateView):
    model = StockEntryLine
    form_class = StockEntryLineForm
    template_name = 'stock/edit_line.html'
    pk_url_kwarg = 'pk'
    permission_required = 'stockentryline.change_stockentryline'

    def get_success_url(self):
        line = StockEntryLine.objects.get(pk=self.kwargs['pk'])
        return reverse('stock:detail', kwargs={'pk':line.parent.id})


class StockEntryLineDelete(BaseView, DeleteView):
    model = StockEntryLine
    template_name = 'stock/delete_line.html'
    pk_url_kwarg = 'pk'
    permission_required = 'stockentryline.delete_stockentryline'

    def get_success_url(self):
        return reverse('stock:detail', kwargs={'pk':self.object.parent.id})

mysite/stock/templates/stock/add_line.html
{% load static %}
{% block add_line %}
<script src="{% static 'js/stock.js' %}" type="text/javascript"></script>
<link href="{% static 'css/stock.css' %}" rel="stylesheet" />
<form action="{% url 'stock:add_line' %}" method='POST'>
  <div class="modal-header">
    <h5 class="modal-title">Add Item</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    {% csrf_token %}
    {{form.as_table}}
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">
      Add
    </button>
  </div>
</form>
{% endblock add_line %}

mysite/stock/templates/stock/create.html
{% extends 'main/main.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/stock.js' %}" type="text/javascript"></script>
<link href="{% static 'css/stock.css' %}" rel="stylesheet" />
<div class="container rounded border border-black mx-auto mt-2">
  <form method="post">{% csrf_token %}
    <div class="row">
      <div class="col">
        {{ form.type.label }}
        {{ form.type }}
      </div>
      <div class="col">
        {{ form.date.label }}
        {{ form.date }}
      </div>
    </div>
    <div class="row">
      <div class="col">
      </div>
      <div class="col">
      </div>
    </div>
    <button type="submit" class="btn btn-success mt-2">
      Create
    </button>
  </form>
</div>
{% endblock content %}

mysite/stock/templates/stock/delete_line.html
{% load static %}
{% block delete_line %}
<script src="{% static 'js/stock.js' %}" type="text/javascript"></script>
<link href="{% static 'css/stock.css' %}" rel="stylesheet" />
<form action="{% url 'stock:delete_line' pk=object.id %}" method='POST'>
  <div class="modal-header">
    <h5 class="modal-title">Delete Item</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    {% csrf_token %}
    <a>Confirm remove: <b>{{object.item}}</b></a>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Confirm</button>
  </div>
</form>
{% endblock delete_line %}

mysite/stock/templates/stock/detail.html
{% extends 'main/main.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/stock.js' %}" type="text/javascript"></script>
<link href="{% static 'css/stock.css' %}" rel="stylesheet" />
<div class="container-fluid rounded border border-dark mt-2 p-2">
  <div class='row p-1'>
    <div class=' col-8'>
      <div class="row">
        <h3> Stock Entry {{ object.code }}
      </div>
      <div class="row">
        <div class="col-4">
          {{ object.date.label }}
          {{ object.date }}
        </div>
        <div class="col-4">
          {{ object.status.label }}
          {{ object.status }}
        </div>
      </div>
      <div class="row">
        <div class="col-4">
          {% if object.parent %}
            <a href="{% url 'invoice:detail' object.parent.id %}">
          {% endif %}
          {{ object.parent.label }}
          {{ object.parent }}
          </a>
        </div>
        <div class="col-4">
          {{ object.type.label }}
          {{ object.get_type_display }}
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="row p-1">
        <div class="col-8">
        </div>
        {% if object.status == 'draft' %}
          <div class="col-4 container rounded border text-center bg-secondary">
        {% elif object.status == 'submitted' %}
          <div class="col-4 container rounded border text-center bg-primary">
        {% elif object.status == 'cancelled' %}
          <div class="col-4 container rounded border text-center bg-danger">
        {% endif %}
          <b>{{ object.get_status_display }}</b>
        </div>
      </div>
    </div>
  </div>

  <div class"row p-2">
    <div class="col-12 container-fluid rounded border border-dark">
      <table class="table table-hover border-dark mb-0">
        <thead>
          {% if object.status == 'draft' %}
            <th style="width:50%;">Code</th>
            <th class="text-end" style="width:15%;">QTY</th>
            <th class="text-end" style="width:15%;">Price</th>
            <th class="text-end" style="width:15%;">Total</th>
            <th class="text-end" style="width:5%;"></th>
          {% else %}
            <th style="width:55%;">Code</th>
            <th class="text-end" style="width:15%;">QTY</th>
            <th class="text-end" style="width:15%;">Price</th>
            <th class="text-end" style="width:15%;">Total</th>
          {% endif %}
        </thead>
        <tbody>
          {% for line in lines %}
            {% if object.status == 'draft' %}
              <tr onclick="edit_line({{line.id}})">
            {% else %}
              <tr>
            {% endif %}
            {% if object.status == 'draft' %}
              <td class="hidden">{{ line.id }}</td>
              <td style="width:50%;">{{ line.item }}</td>
              <td class="text-end" style="width:15%;">{{ line.qty }}</td>
              <td class="text-end" style="width:15%;">{{ line.price }}</td>
              <td class="text-end" style="width:15%;">{{ line.total }}</td>
              <td class="text-end" style="width:5%;">
                <div>
                  <span onclick="delete_line({{line.id}})" type="button" class="material-icons">
                    delete
                  </span>
                </div>
              </td>
              {% else %}
              <td class="hidden">{{ line.id }}</td>
              <td style="width:55%;">{{ line.item }}</td>
              <td class="text-end" style="width:15%;">{{ line.qty }}</td>
              <td class="text-end" style="width:15%;">{{ line.price }}</td>
              <td class="text-end" style="width:15%;">{{ line.total }}</td>
              {% endif %}
          </tr>
          {% endfor %}
          <tr class="text-end">
            <td></td>
            <td></td>
            <td>Total:</td>
            <td>{{ object.total }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row p-2">
    <div class=" col-8">
    </div>
    <div class="col-4 container rounded border border-dark">
      <table class="table mb-0 border-dark">
        <tr>
          <td>Total:</td>
          <td>{{ object.total }}</td>
        </tr>
        <tr>
          <td>Payments:</td>
          <td>0.0</td>
        </tr>
        <tr>
          <td>Outstanding:</td>
          <td>0.0</td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row p-0 mb-1">
    {% if object.status == 'draft' %}
    <div class="col-6">
      <button onclick="add_line({{object.id}})" id="add-item-btn" type="button" class="btn btn-primary">
        Add Item
      </button>
    </div>
    <div class="col-6">
      <button id="submit-modal-btn" type="button" class="btn btn-success mt-2 pull-right" data-bs-toggle="modal"
        data-bs-target="#submitSteModal">
        Submit
      </button>
    </div>
    {% endif %}
    {% if object.status == 'submitted' %}
    <div class="col-12">
      <button id="cancel-modal-btn" type="button" class="btn btn-danger mt-2 pull-right" data-bs-toggle="modal"
        data-bs-target="#cancelSteModal">
        Cancel
      </button>
    </div>
    {% endif %}
  <div>

  <!-- Item Modal -->
  <div class="modal fade" id="itemModal" tabindex="-1" aria-labelledby="itemModal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content" id="item-modal-content">
          <!-- ITEM -->
      </div>
    </div>
  </div>

  <!-- Submit Modal -->
  <div class="modal fade" id="submitSteModal" tabindex="-1" aria-labelledby="submitSteModal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Submit ?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="{% url 'stock:submit' pk=object.id%}" method='POST'>
            {% csrf_token %}
            <div class="row">
              <div class="col-6">
                <h5> {{ object.code }} </h5>
              </div>
              <div class="col-6">
                <div class="pull-right">
                  <button type="submit" class="btn btn-primary">Yes</button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <!-- Cancel Modal -->
  <div class="modal fade" id="cancelSteModal" tabindex="-1" aria-labelledby="cancelSteModal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Cancel ?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="{% url 'stock:cancel' pk=object.id%}" method='POST'>
            {% csrf_token %}
            <div class="row">
              <div class="col-6">
                <h5> {{ object.code }} </h5>
              </div>
              <div class="col-6">
                <div class="pull-right">
                  <button type="submit" class="btn btn-primary">Yes</button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

</div>
{% endblock content %}

mysite/stock/templates/stock/edit_line.html
{% load static %}
{% block edit_line %}
<script src="{% static 'js/stock.js' %}" type="text/javascript"></script>
<link href="{% static 'css/stock.css' %}" rel="stylesheet" />
<form action="{% url 'stock:edit_line' pk=object.id %}" method='POST'>
  <div class="modal-header">
    <h5 class="modal-title">Edit Item</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    {% csrf_token %}
    {{form.as_table}}
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">
      Save
    </button>
  </div>
</form>
{% endblock edit_line %}

mysite/stock/templates/stock/list.html
{% extends 'main/main.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/stock.js' %}" type="text/javascript"></script>
<link href="{% static 'css/stock.css' %}" rel="stylesheet" />
<div class="container-fluid rounded border border-dark mt-2">
  <table class="table table-hover mb-0">
    <thead>
      <th style="width:30%">Code</th>
      <th style="width:20%">Date</th>
      <th style="width:20%">Parent</th>
      <th class="text-center" style="width:10%">Type</th>
      <th class="text-center" style="width:10%">Status</th>
    </thead>
    <tbody>
      {% for stock in object_list %}
      <tr onclick="window.location='detail/{{stock.id}}'")>
        <td style="width:20%">{{ stock.code }}</td>
        <td style="width:20%">{{ stock.date }}</td>
        <td style="width:20%">{{ stock.parent }}</td>
        <td class="text-center" style="width:10%">{{ stock.get_type_display }}</td>
        <td class="text-center" style="width:10%">
          {% if stock.status == 'draft' %}
            <div class="bg-secondary text-white text-center border border-dark rounded">
          {% elif stock.status == 'submitted' %}
            <div class="bg-primary text-white text-center border border-dark rounded">
          {% elif stock.status == 'cancelled' %}
            <div class="bg-danger text-white text-center border border-dark rounded">
          {% endif %}
            {{ stock.get_status_display }}
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% include 'main/footer.html' %}
</div>
{% endblock content %}