mysite/invoice/urls.py
from django.urls import path
from .views import *

app_name = "invoice"
urlpatterns = [
    path('', InvoiceList.as_view(), name='list'),
    path('detail/<int:pk>', InvoiceDetail.as_view(), name='detail'),
    path('edit/<int:pk>', InvoiceUpdate.as_view(), name='edit'),
    path('submit/<int:pk>', InvoiceUpdate.as_view(), {'process': 'submit'}, name='submit'),
    path('cancel/<int:pk>', InvoiceUpdate.as_view(), {'process': 'cancel'}, name='cancel'),
    path('create/', InvoiceCreate.as_view(), name='create'),

    path('add_line/', InvoiceLineCreate.as_view(), name='add_line'),
    path('delete_line/<int:pk>', InvoiceLineDelete.as_view(), name='delete_line'),
    path('edit_line/<int:pk>', InvoiceLineEdit.as_view(), name='edit_line'),

    path('create_stockentry/<int:invo_id>', CreateStockEntry.as_view(), name='create_stockentry'),
    path('list_stockentry/<int:invo_id>', ListStockEntry.as_view(), name='create_sotckentry'),
]

mysite/main/urls.py
from django.urls import path, include
from .views import MainView, MainLoginView
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('login/', MainLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='main_url'), name='logout'),
    path('', MainView.as_view(), name='main_url'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('invoice/', include('invoice.urls')),
    path('payment/', include('payment.urls')),
    path('partner/', include('partner.urls')),
    path('stock/', include('stock.urls')),
    path('', include('main.urls')),
]

mysite/partner/urls.py
from django.urls import path
from .views import *

app_name = "partner"
urlpatterns = [
    path('', PartnerList.as_view(), name='list'),
    path('create/', PartnerCreate.as_view(), name='create'),
    # path('detail/<int:pk>', PartnerDetail.as_view(), name='detail'),
    path('edit/<int:pk>', PartnerUpdate.as_view(), name='edit'),
    path('delete/<int:pk>', PartnerDelete.as_view(), name='delete'),
]

mysite/payment/urls.py
from django.urls import path
from .views import *

app_name = "payment"
urlpatterns = [
    path('', PaymentList.as_view(), name='list'),
    path('detail/<int:pk>', PaymentDetail.as_view(), name='detail'),
    path('edit/<int:pk>', PaymentUpdate.as_view(), name='edit'),
    path('submit/<int:pk>', PaymentUpdate.as_view(), {'process': 'submit'}, name='submit'),
    path('cancel/<int:pk>', PaymentUpdate.as_view(), {'process': 'cancel'}, name='cancel'),
    path('create/', PaymentCreate.as_view(), name='create'),

    path('add_line/', PaymentLineCreate.as_view(), name='add_line'),
    path('delete_line/<int:pk>', PaymentLineDelete.as_view(), name='delete_line'),
    path('edit_line/<int:pk>', PaymentLineEdit.as_view(), name='edit_line'),
]

mysite/stock/urls.py
from django.urls import path
from .views import *

app_name = "stock"
urlpatterns = [
    path('', StockEntryList.as_view(), name='list'),
    path('detail/<int:pk>', StockEntryDetail.as_view(), name='detail'),
    # path('edit/<int:pk>', StockEntryUpdate.as_view(), name='edit'),
    path('submit/<int:pk>', StockEntryUpdate.as_view(), {'process': 'submit'}, name='submit'),
    path('cancel/<int:pk>', StockEntryUpdate.as_view(), {'process': 'cancel'}, name='cancel'),
    path('create/', StockEntryCreate.as_view(), name='create'),

    path('add_line/', StockEntryLineCreate.as_view(), name='add_line'),
    path('edit_line/<int:pk>', StockEntryLineEdit.as_view(), name='edit_line'),
    path('delete_line/<int:pk>', StockEntryLineDelete.as_view(), name='delete_line'),
]

mysite/main/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager

NAMING_TYPE = [
    ('default', 'Default'),
    ('in', 'In'),
    ('out', 'Out'),
]

DOC_STATUS = [
    ('0', 'Draft'),
    ('1', 'Submitted'),
    ('2', 'Cancelled'),
]

class Main(models.Model):
    title = models.CharField(max_length=140)


class NamingSeries(models.Model):
    serie = models.CharField(max_length=10)
    type = models.CharField(choices=NAMING_TYPE, default='default', null=True, max_length=10)
    number = models.IntegerField(default=1)
    fill = models.IntegerField(default=4)

    @classmethod
    def get_series(cls, serie=None, type='default'):
        get_s = cls.objects.get_or_create(serie=serie, type=type)
        s = get_s[0]
        if get_s[1]:
            return str(serie) +' - ' + str(s.number).zfill(s.fill)
        else:
            s.number = int(s.number) + 1
            s.save()
            return str(serie) +' - ' + str(s.number).zfill(s.fill)


class MainAccontManager(BaseUserManager):
    def create_user(self, email, user_name, password, **other_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, user_name=user_name, **other_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, user_name, password, **other_fields):
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_manager', True)
        other_fields.setdefault('is_active', True)
        
        return self.create_user(email, user_name, password, is_superuser=True, **other_fields)


class MainUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    user_name = models.CharField(max_length=50, unique=True)
    create_date = models.DateField(default=timezone.now)

    is_manager = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    objects = MainAccontManager()

    USERNAME_FIELD = 'user_name'
    REQUIRED_FIELDS = ['email']


class MainDoc(models.Model):
    status = models.IntegerField(choices=DOC_STATUS, default=0, null=True, max_length=1)
    date = models.DateField(default=timezone.now)
    post_date = models.DateField(default=timezone.now)
    created_by = models.ForeignKey(MainUser, related_name='%class)s_created', on_delete=models.SET_NULL, null=True)
    last_modify = models.ForeignKey(MainUser, related_name='%(class)s_modify', on_delete=models.SET_NULL, null=True)

    class Meta:
        abstract = True

mysite/main/views.py
from django.shortcuts import render
from django.views.generic import View
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


class BaseView(LoginRequiredMixin, PermissionRequiredMixin):
    pass


class MainLoginView(LoginView):
    template_name = 'main/mainlogin.html'
    fields = '__all__'
    redirect_authenticated_user = True
    permission_required = None

    def get_redirect_url(self):
        return reverse_lazy('main_url')

class MainView(LoginRequiredMixin, View):
    def get(self, request):

        return render(request, 'main/main.html')

mysite/main/templates/main/footer.html
<div class="row mt-1">
  <div class="col-6">
    <nav aria-label="Pagination Bar">
      <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
          <a class="page-link" href="#">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        {% endif %}
        <li class="page-item active">
          <a class="page-link" href="#">{{page_obj.number}}</a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
        {% else %}
        <li class="page-item">
          <a class="page-link" href="#">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
  </div>
  <div class="col-6 text-end">
    <a href="create/" type="button" class="btn btn-success">
      Create
    </a>
  </div>
</div>

mysite/main/templates/main/main.html
{% load static %}
<DOCTYPE html>
<html lang="en">
	<head>
    <!-- JQUERY  -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" 
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" 
    crossorigin="anonymous"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
      crossorigin="anonymous">
      <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
      crossorigin="anonymous">
    </script>
    <!-- SELECT2 -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <!-- Icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>
  <body>
    {% include 'main/navbar.html' %}
    <div class="row">
      <div class="col-2">
      </div>
      <div class="col-9">
        {% block content %}

        {% endblock content %}
      </div>
      <div class="col-1">
      </div>
    </div>
  </body>
</html>

mysite/main/templates/main/mainlogin.html
{% extends 'main/main.html' %}
{% load static %}
{% load custom_tags %}
{% block content %}
<link href="{% static 'css/main.css' %}" rel="stylesheet" />
  <div class="container py-5 h-100">
    <div class="row d-flex align-items-center justify-content-center h-100">
      <div class="col-md-8 col-lg-7 col-xl-6">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.svg"
          class="img-fluid" alt="Phone image">
      </div>
      <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
        <form method="POST">
          {% csrf_token %}
          <div class="form-outline mb-4">
            {{ form.username | addclass:"form-control" }}
            <label class="form-label" for="id_username">User</label>
            <!-- <input type="email" id="form1Example13" class="form-control form-control-lg" /> -->
          </div>
          <div class="form-outline mb-4">
            {{ form.password | addclass:"form-control" }}
            <label class="form-label" for="id_password">Password</label>
            <!-- <input type="password" id="form1Example23" class="form-control form-control-lg" /> -->
          </div>

          <!-- Submit button -->
          <button type="submit" class="btn btn-primary btn-lg btn-block">Login</button>

        </form>
      </div>
    </div>
  </div>
{% endblock content %}

mysite/main/templates/main/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="prodDrop" role="button" data-bs-toggle="dropdown"
          aria-expanded="false">
          Products
        </a>
        <ul class="dropdown-menu" aria-labelledby="prodDrop">
          <li><a class="dropdown-item" href="{% url 'product:list' %}">List</a></li>
          <li><a class="dropdown-item" href="{% url 'product:create' %}">Create</a></li>
        </ul>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="invoDrop" role="button" data-bs-toggle="dropdown"
          aria-expanded="false">
          Invoices
        </a>
        <ul class="dropdown-menu" aria-labelledby="invoDrop">
          <li><a class="dropdown-item" href="{% url 'invoice:list' %}">List</a></li>
          <li><a class="dropdown-item" href="{% url 'invoice:create' %}">Create</a></li>
        </ul>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="partnerDrop" role="button" data-bs-toggle="dropdown"
          aria-expanded="false">
          Partner
        </a>
        <ul class="dropdown-menu" aria-labelledby="partnerDrop">
          <li><a class="dropdown-item" href="{% url 'partner:list' %}">List</a></li>
          <li><a class="dropdown-item" href="{% url 'partner:create' %}">Create</a></li>
        </ul>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="partnerDrop" role="button" data-bs-toggle="dropdown"
          aria-expanded="false">
          Stock
        </a>
        <ul class="dropdown-menu" aria-labelledby="partnerDrop">
          <li><a class="dropdown-item" href="{% url 'stock:list' %}">List</a></li>
          <li><a class="dropdown-item" href="{% url 'stock:create' %}">Create</a></li>
        </ul>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="paymentDrop" role="button" data-bs-toggle="dropdown"
          aria-expanded="false">
          Payment
        </a>
        <ul class="dropdown-menu" aria-labelledby="paymentDrop">
          <li><a class="dropdown-item" href="{% url 'payment:list' %}">List</a></li>
          <li><a class="dropdown-item" href="{% url 'payment:create' %}">Create</a></li>
        </ul>
      </li>
    </ul>
  </div>
  {% if user.is_authenticated %}
  <a class="navbar-end" href="/logout">Logout</a>
  {% endif %}
</nav>