mysite/main/urls.py
from django.urls import path, include
from .views import MainView, MainLoginView
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('login/', MainLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='main_url'), name='logout'),
    path('', MainView.as_view(), name='main_url'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('invoice/', include('invoice.urls')),
    path('payment/', include('payment.urls')),
    path('partner/', include('partner.urls')),
    path('stock/', include('stock.urls')),
    path('', include('main.urls')),
]

mysite/payment/urls.py
from django.urls import path
from .views import *

app_name = "payment"
urlpatterns = [
    path('', PaymentList.as_view(), name='list'),
    path('detail/<int:pk>', PaymentDetail.as_view(), name='detail'),
    path('edit/<int:pk>', PaymentUpdate.as_view(), name='edit'),
    path('submit/<int:pk>', PaymentUpdate.as_view(), {'process': 'submit'}, name='submit'),
    path('cancel/<int:pk>', PaymentUpdate.as_view(), {'process': 'cancel'}, name='cancel'),
    path('create/', PaymentCreate.as_view(), name='create'),

    path('add_line/', PaymentLineCreate.as_view(), name='add_line'),
    path('delete_line/<int:pk>', PaymentLineDelete.as_view(), name='delete_line'),
    path('edit_line/<int:pk>', PaymentLineEdit.as_view(), name='edit_line'),
]

mysite/payment/models.py
from partner.models import Partner
from invoice.models import Invoice
from django.db import models
from main.models import NamingSeries as NS


PAY_TYPE = [
    ('pay', 'Pay'),
    ('receipt', 'Receipt'),
]
PAY_STATUS = [
    ('draft', 'Draft'),
    ('submitted', 'Submitted'),
    ('cancelled', 'Cancelled'),
]

class Payment(models.Model):
    code = models.CharField(max_length=12, null=True)
    date = models.DateField(null=True)
    partner = models.ForeignKey(Partner, related_name='payment_partner', on_delete=models.SET_NULL, null=True)
    type = models.CharField(choices=PAY_TYPE, default='', null=True, max_length=10)
    status = models.CharField(choices=PAY_STATUS, default='draft', null=True, max_length=10)
    total = models.DecimalField(default=0.0, decimal_places=2, max_digits=12)

    class Meta:
        ordering = ['code']

    def __str__(self):
        return self.code

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.id:
            self.code = NS.get_series(serie='PE')
        return super().save(force_insert, force_update, using, update_fields)

    def get_absolute_url(self):
        return reverse('paymenentry:detail', args=[self.id])

    def submit_payment(self):
        if self.status == 'draft':
            self.status = 'submitted'
            lines = self.payment_line.all()
            print(lines)
            for line in lines:
                line.submit_pay_line()
                line.save()
            self.save()

    def cancel_payment(self):
        if self.status == 'submitted':
            self.status = 'cancelled'
            lines = self.payment_line.all()
            for line in lines:
                line.cancel_pay_line()
                line.save()
            self.save()


class PaymentLine(models.Model):
    item = models.ForeignKey(Invoice, related_name='pay_line_invo', on_delete=models.SET_NULL, null=True)
    parent = models.ForeignKey(Payment, related_name='payment_line', on_delete=models.SET_NULL, null=True)
    type = models.CharField(choices=PAY_TYPE, default='', null=True, max_length=10)
    status = models.CharField(choices=PAY_STATUS, default='draft', null=True, max_length=10)
    total = models.DecimalField(default=0.0, decimal_places=2, max_digits=12)
    allocated = models.DecimalField(default=0.0, decimal_places=2, max_digits=12)
    outstanding = models.DecimalField(default=0.0, decimal_places=2, max_digits=12)

    def submit_pay_line(self):
        if self.status == 'draft':
            self.status = 'submitted'
            self.outstanding = self.outstanding + self.allocated
        
    def cancel_pay_line(self):
        if self.status == 'submitted':
            self.status = 'cancelled'
            self.outstanding = self.outstanding - self.allocated

mysite/payment/forms.py
from django import forms
from .models import Payment, PaymentLine


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = [
            'date',
            'partner',
            'type',
        ]
        widgets = {
                'date': forms.DateInput(attrs={'class': 'form-control container col', 'type': 'date'}),
                'partner': forms.Select(attrs={'class': 'form-control'}),
                'type': forms.Select(attrs={'class': 'form-control'}),
                }


class PaymentLineForm(forms.ModelForm):
    class Meta:
        model = PaymentLine
        fields = [
            'item',
            'parent',
            'outstanding',
            'allocated',
            'total',
        ]
        widgets = {
            'parent': forms.HiddenInput(),
        }

mysite/payment/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Payment, PaymentLine
from .forms import PaymentForm, PaymentLineForm
from django.urls import reverse
from django.shortcuts import redirect
from django.http import HttpResponseForbidden
from main.views import BaseView

class PaymentList(BaseView, ListView):
    model = Payment
    template_name = 'payment/list.html'
    paginate_by = 20
    permission_required = 'payment.view_payment'


class PaymentDetail(BaseView, DeleteView):
    model = Payment
    template_name = 'payment/detail.html'
    form_class = PaymentForm
    pk_url_kwarg = 'pk'
    permission_required = 'payment.delete_payment'

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        lines = PaymentLine.objects.all().filter(parent=self.kwargs['pk'])
        context['lines'] = lines
        return context


class PaymentCreate(BaseView, CreateView):
    model = Payment
    form_class = PaymentForm
    template_name = 'payment/create.html'
    permission_required = 'parent.add_payment'

    def get_success_url(self):
        return reverse('payment:detail', kwargs={'pk':self.object.id})


class PaymentUpdate(BaseView, UpdateView):
    model = Payment
    form_class = PaymentForm
    template_name = 'payment/detail.html'
    fields = "__all__"
    pk_url_kwarg = 'pk'
    permission_required = 'parent.change_payment'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lines = PaymentLine.objects.all().filter(parent=self.kwargs['pk'])
        new_line = PaymentLineForm(initial={'parent':self.object})
        context['new_line'] = new_line
        context['lines'] = lines
        return context

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        if kwargs.get('process') == 'submit':
            obj.submit_payment()
        
        if kwargs.get('process') == 'cancel':
            obj.cancel_payment()

        return redirect('payment:detail', pk=obj.id)


class PaymentLineCreate(BaseView, CreateView):
    model = PaymentLine
    form_class = PaymentLineForm
    template_name = 'payment/add_line.html'
    pk_url_kwarg = 'pk'
    permission_required = 'parentline.add_paymentline'

    def post(self, request, *args, **kwargs):
        return super(PaymentLineCreate, self).post(request, *args, **kwargs)

    def get_success_url(self):
        pk = self.request.POST['parent']
        return reverse('payment:detail', kwargs={'pk':pk})


class PaymentLineEdit(BaseView, UpdateView):
    model = PaymentLine 
    form_class = PaymentLineForm
    template_name = 'payment/edit_line.html'
    pk_url_kwarg = 'pk'
    permission_required = 'parentline.change_paymentline'

    def get_success_url(self):
        line = PaymentLine.objects.get(pk=self.kwargs['pk'])
        return reverse('payment:detail', kwargs={'pk':line.parent.id})


class PaymentLineDelete(BaseView, DeleteView):
    model = PaymentLine
    template_name = 'payment/delete_line.html'
    pk_url_kwarg = 'pk'
    permission_required = 'parentline.delete_paymentline'

    def dispatch(self, request, *args, **kwargs):
        handler = getattr(self, 'delete')
        return handler(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('payment:detail', kwargs={'pk':self.object.parent.id})

mysite/payment/templates/payment/add_line.html
{% load static %}
{% block add_line %}
<script src="{% static 'js/payment.js' %}" type="text/javascript"></script>
<link href="{% static 'css/payment.css' %}" rel="stylesheet" />
<form action="{% url 'payment:add_line' %}" method='POST'>
  <div class="modal-header">
    <h5 class="modal-title">Add Invoice</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    {% csrf_token %}
    {{form.as_table}}
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Add</button>
  </div>
</form>
{% endblock add_line %}

mysite/payment/templates/payment/create.html
{% extends 'main/main.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/payment.js' %}" type="text/javascript"></script>
<link href="{% static 'css/payment.css' %}" rel="stylesheet" />
<div class="container rounded border mt-2">
  <form method="post">{% csrf_token %}
    <div class="row">
      <div class="col-6">
        {{ form.type.label }}
        {{ form.type }}
      </div>
      <div class="col-6">
        {{ form.date.label }}
        {{ form.date }}
      </div>
    </div>
    <div class="row">
      <div class="col-6">
        {{ form.partner.label }}
        {{ form.partner }}
      </div>
      <div class="col-6">
      </div>
    </div>
    <button type="submit" class="btn btn-success mt-2">
      Save
    </button>
  </form>
</div>
{% endblock content %}

mysite/payment/templates/payment/delete_line.html
{% load static %}
{% block delete_line %}
<script src="{% static 'js/payment.js' %}" type="text/javascript"></script>
<link href="{% static 'css/payment.css' %}" rel="stylesheet" />
<form action="{% url 'payment:delete_line' pk=object.id %}" method='POST'>
  <div class="modal-header">
    <h5 class="modal-title">Delete Item</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    {% csrf_token %}
    <a>Confirm remove: <b>{{object.item}}</b></a>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Confirm</button>
  </div>
</form>
{% endblock delete_line %}

mysite/payment/templates/payment/detail.html
{% extends 'main/main.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/payment.js' %}" type="text/javascript"></script>
<link href="{% static 'css/payment.css' %}" rel="stylesheet" />
<div class="container-fluid rounded border border-dark mt-2 p-2">
  <div class="row p-1">
    <div class="col-8">
      <div class="row">
        <h3>Payment {{ object.code }}</h3>
      </div>
      <div class="row">
        <div class="col-4">
          {{ object.date.label }}
          {{ object.date }}
        </div>
        <div class="col-4">
          {{ object.status.label }}
          {{ object.get_status_display }}
        </div>
      </div>
      <div class="row">
        <div class="col-4">
          {{ object.partner.label }}
          {{ object.partner }}
        </div>
        <div class="col-4">
          {{ object.type.label }}
          {{ object.get_type_display }}
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="row p-1">
        <div class="col-8">
        </div>
        {% if object.status == 'draft' %}
        <div class="col-4 container rounded border text-center bg-secondary">
          {% elif object.status == 'submitted' %}
          <div class="col-4 container rounded border text-center bg-primary">
            {% elif object.status == 'cancelled' %}
            <div class="col-4 container rounded border text-center bg-danger">
              {% endif %}
              <b>{{ object.get_status_display }}</b>
            </div>
          </div>
          {% if object.status == 'submitted' %}
          <div class="row p-1">
            <div class="col-8">
            </div>
            {% if object.qty_status == 'pending' %}
            <div onclick="list_ste({{object.id}})"
              class="col-4 container rounded border border-dark text-center bg-secondary">
              {% elif object.qty_status == 'partial' %}
              <div onclick="list_ste({{object.id}})"
                class="col-4 container rounded border border-dark text-center bg-warning">
                {% elif object.qty_status == 'complete' %}
                <div onclick="list_ste({{object.id}})"
                  class="col-4 container rounded border border-dark text-center bg-success">
                  {% endif %}
                  <b class="fs-5">
                    <span class="material-icons align-middle">
                      local_shipping more_vert
                    </span>
                    {{ object.get_ste_count}}

                  </b>
                </div>
              </div>
              <div class="row p-1">
                <div class="col-8">
                </div>
                <div class="col-4 container rounded border border-dark text-center">
                  <b class="fs-5">
                    <span class="material-icons align-middle">
                      payments more_vert
                    </span>
                    0
                  </b>
                </div>
              </div>
              {% endif %}
            </div>
          </div>
          <!-- <div class="container rounded border p-1"> -->
          <div class="row p-2">
            <div class="col-12 container-fluid rounded border border-dark">
              <table class="table table-hover border-dark mb-0">
                <thead>
                  {% if object.status == 'draft' %}
                  <th style="width:50%">Code</th>
                  <th class="text-end" style="width:15%">Total</th>
                  <th class="text-end" style="width:15%">Outstanding</th>
                  <th class="text-end" style="width:15%">Allocated</th>
                  <th class="text-end" style="width:5%"></th>
                  {% else %}
                  <th style="width:55%">Code</th>
                  <th class="text-end" style="width:15%">Total</th>
                  <th class="text-end" style="width:15%">Outstanding</th>
                  <th class="text-end" style="width:15%">Allocated</th>
                  {% endif %}
                </thead>
                <tbody>
                  {% for line in lines %}
                  {% if object.status == 'draft' %}
                  <tr onclick="edit_line({{line.id}})">
                    {% else %}
                  <tr>
                    {% endif %}
                    {% if object.status == 'draft' %}
                    <td class="hidden">{{ line.id }}</td>
                    <td style="width:50%">{{ line.item }}</td>
                    <td class="text-end" style="width:15%">{{ line.total }}</td>
                    <td class="text-end" style="width:15%">{{ line.outstanding }}</td>
                    <td class="text-end" style="width:15%">{{ line.allocated }}</td>
                    <td class="text-end" style="width:5%">
                      <div>
                        <span onclick="delete_line({{line.id}})" type="button" class="material-icons">
                          delete
                        </span>
                    </td>
                    {% else %}
                    <td class="hidden">{{ line.id }}</td>
                    <td style="width:55%">{{ line.item }}</td>
                    <td class="text-end" style="width:15%">{{ line.total }}</td>
                    <td class="text-end" style="width:15%">{{ line.outstanding }}</td>
                    <td class="text-end" style="width:15%">{{ line.allocated }}</td>
                    {% endif %}
                  </tr>
                  {% endfor %}
                  <tr class="text-end">
                    <td></td>
                    <td></td>
                    <td>Total:</td>
                    <td>{{ object.total }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div class="row p-2">
            <div class=" col-8">
            </div>
            <div class="col-4 container rounded border border-dark">
              <table class="table mb-0 border-dark">
                <tr>
                  <td>Total:</td>
                  <td>{{ object.total }}</td>
                </tr>
                <tr>
                  <td>Payments:</td>
                  <td>0.0</td>
                </tr>
                <tr>
                  <td>Outstanding:</td>
                  <td>0.0</td>
                </tr>
              </table>
            </div>
          </div>

          <div class="row p-0 mb-1">
            {% if object.status == 'draft' %}
            <div class="col-6">
              <button onclick="add_line({{object.id}})" id="add-item-btn" type="button" class="btn btn-primary">
                Add Item
              </button>
            </div>
            <div class="col-6">
              <button id="submit-modal-btn" type="button" class="btn btn-success pull-right" data-bs-toggle="modal"
                data-bs-target="#submitPatmentModal">
                Submit
              </button>
            </div>
            {% endif %}
            {% if object.status == 'submitted' %}
            <div class="col-12">
              <button id="cancel-modal-btn" type="button" class="btn btn-danger pull-right" data-bs-toggle="modal"
                data-bs-target="#cancelPatmentModal">
                Cancel
              </button>
            </div>
            {% endif %}
            <div>

              <!-- Item Modal -->
              <div class="modal fade" id="itemModal" data-backdrop="true" tabindex="-1" aria-labelledby="itemModal"
                aria-hidden="true">
                <div class="modal-dialog modal-lg">
                  <div class="modal-content" id="item-modal-content">
                    <!-- ITEM -->
                  </div>
                </div>
              </div>

              <!-- Submit Modal -->
              <div class="modal fade" id="submitPatmentModal" tabindex="-1" aria-labelledby="submitpaymentModal"
                aria-hidden="true">
                <div class="modal-dialog modal-lg">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title">Submit ?</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <form action="{% url 'payment:submit' pk=object.id%}" method='POST'>
                        {% csrf_token %}
                        <div class="row">
                          <div class="col-6">
                            <h5> {{ object.code }} </h5>
                          </div>
                          <div class="col-6">
                            <div class="pull-right">
                              <button type="submit" class="btn btn-primary">Yes</button>
                            </div>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>

              <!-- Cancel Modal -->
              <div class="modal fade" id="cancelPatmentModal" tabindex="-1" aria-labelledby="cancelSteModal"
                aria-hidden="true">
                <div class="modal-dialog modal-lg">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title">Cancel ?</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <form action="{% url 'payment:cancel' pk=object.id%}" method='POST'>
                        {% csrf_token %}
                        <div class="row">
                          <div class="col-6">
                            <h5> {{ object.code }} </h5>
                          </div>
                          <div class="col-6">
                            <div class="pull-right">
                              <button type="submit" class="btn btn-primary">Yes</button>
                            </div>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>

            </div>
            {% endblock content %}

mysite/payment/templates/payment/edit_line.html
{% load static %}
{% block add_line %}
<script src="{% static 'js/payment.js' %}" type="text/javascript"></script>
<link href="{% static 'css/payment.css' %}" rel="stylesheet" />
<form action="{% url 'payment:edit_line' pk=object.id %}" method='POST'>
  <div class="modal-header">
    <h5 class="modal-title">Add Invoice</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    {% csrf_token %}
    {{ form.parent }}
    <div class="row">
      <div class="col-6">
        {{ form.item.label }}
        {{ form.item }}
      </div>
      <div class="col-6">
        {{ form.allocated.label }}
        {{ form.allocated }}
      </div>
    </div>
    <div class="row">
      <div class="col-6">
        {{ form.total.label}}
        {{ form.total}}
      </div>
      <div class="col-6">
        {{ form.outstanding.label }}
        {{ form.outstanding }}
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <span onclick="delete_line({'id':'{{object.id}}','token':'{{csrf_token}}'})" type="button" class="btn btn-danger">
      Delete
    </span>
    <button type="submit" class="btn btn-primary">Add</button>
  </div>
</form>
{% endblock add_line %}

mysite/payment/templates/payment/list.html
{% extends 'main/main.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/payment.js' %}" type="text/javascript"></script>
<link href="{% static 'css/payment.css' %}" rel="stylesheet" />
<div class="container rounded border border-dark mt-2">
  <table class="table table-hover mb-0">
    <thead>
      <th style="width:15%">Code</th>
      <th style="width:15%">Date</th>
      <th style="width:30%">Partner</th>
      <th style="width:10%" class="text-center">Type</th>
      <th style="width:10%" class="text-center">Status</th>
      <th style="width:10%">Total</th>
    </thead>
    <tbody>
      {% for payment in object_list %}
      <tr onclick="window.location='detail/{{payment.id}}'">
        <td style="width:15%">{{ payment.code }}</td>
        <td style="width:15%">{{ payment.date }}</td>
        <td style="width:30%">{{ payment.partner }}</td>
        <td style="width:10%" class="text-center">{{ payment.get_type_display }}</td>
        <td style="width:10%">
          {% if payment.status == 'draft' %}
          <div class="bg-secondary text-white text-center border border-dark rounded">
            {% elif payment.status == 'submitted' %}
            <div class="bg-primary text-white text-center border border-dark rounded">
              {% elif payment.status == 'cancelled' %}
              <div class="bg-danger text-white text-center border border-dark rounded">
                {% endif %}
                {{ payment.get_status_display }}
              </div>
        </td>
        <td style="width:10%">{{ payment.total }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% include 'main/footer.html' %}
</div>
{% endblock content %}